### ISSUE TITLE
Email Regex Pattern Validates Invalid Emails

### ISSUE THREAD

**Issue by rikoschmidt** [steve228uk/SRFormValidator#2]
The regex used in the validator **^[a-zA-Z0-9.!#$%&'_+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)_$** returns "valid" for email addresses like: **first.last@g**. From my point of view this is incorrect. 

Instead one could use the following regex: **[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}**

Please correct me if I am wrong.

**Comment by steve228uk** [comment]
This looks good to me. Do you want to submit a PR for it?

**Comment by rikoschmidt** [comment]
yeah sure :)

**Comment by steve228uk** [comment]
Fixed by #3
